services:
  backend:
    image: cozychat/backend:v0.1.0  
    container_name: cozychat-backend
    restart: unless-stopped
    ports:
      - "9800:8000"
    volumes:
      - /data/cozychat/backend/logs:/opt/cozychat/backend/logs
      - /data/cozychat/backend/data:/opt/cozychat/backend/data
      - /data/cozychat/backend/backend.env:/opt/cozychat/.env:ro
    networks:
      - 1panel-network
    depends_on:
      - qdrant
    labels:
      createdBy: "Apps"

  frontend:
    image: cozychat/frontend:v0.1.0  
    container_name: cozychat-frontend
    restart: unless-stopped
    ports:
      - "8000:5173"
    volumes:
      - /data/cozychat/frontend/dist:/opt/cozychat/frontend/dist
      - /data/cozychat/frontend/frontend.env:/opt/cozychat/frontend/.env:ro
    networks:
      - 1panel-network
    depends_on:
      - backend
    labels:
      createdBy: "Apps"

  qdrant:
    image: qdrant/qdrant:v1.15
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      QDRANT__GPU__INDEXING: 1
    volumes:
      - /data/qdrant/data:/qdrant/storage
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true

