"""add_title_generated_at_to_sessions

Revision ID: 4232b4b50ff0
Revises: 20194414fecb
Create Date: 2025-11-18 10:32:47.958864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4232b4b50ff0'
down_revision = '20194414fecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_messages_user_created'), table_name='messages')
    op.add_column('sessions', sa.Column('title_generated_at', sa.DateTime(), nullable=True, comment='标题生成时间'))
    op.drop_index(op.f('idx_sessions_user_deleted'), table_name='sessions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_sessions_user_deleted_created'), table_name='sessions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_sessions_user_deleted_lastmsg'), table_name='sessions', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('idx_sessions_user_deleted_lastmsg'), 'sessions', ['user_id', 'deleted_at', 'last_message_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_sessions_user_deleted_created'), 'sessions', ['user_id', 'deleted_at', 'created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_sessions_user_deleted'), 'sessions', ['user_id', 'deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('sessions', 'title_generated_at')
    op.create_index(op.f('idx_messages_user_created'), 'messages', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


